site_name: ${artifactId}
theme:
  name: readthedocs

repo_name: DANS-KNAW/${artifactId}
repo_url: https://github.com/DANS-KNAW/${artifactId}

nav:
  - Manual:
      - Description: index.md
      - Installation: installation.md
      - Configuration: config.md
      - API: to-api.md
      - Context: context.md
  - Development:
      - Overview: dev.md

plugins:
  - markdownextradata
  - search

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: False
      use_pygments: False
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: True
